const data = {
  projects: [
    {
      foto: require("./assets/mauaApp.png"),
      name: "Mauápp",
      frontend: "Flutter",
      backend: "Python",
      link: "https://github.com/Maua-Dev/System_Maua_Front",
      membros: [
        {
          ano: "3º",
          area: "Backend",
          curso: "Engenharia de Computação",
          foto: "https://drive.google.com/open?id=1scuuOVD7PE6wUcS7xptpJluGLUQsi4cC",
          githubLink: "https://github.com/AhmadKmahfoud",
          hobby: "Jogar Xadrez",
          linguagens: "",
          linkedinLink: "https://www.linkedin.com/in/ahmad-mahfoud-7ba1b71ab/",
          name: "Ahmad Kheder Mahfoud",
          nascimento: "2002-03-08 00:00:00",
        },
        {
          ano: "3º",
          area: "Frontend, Gerência de Projetos",
          curso: "Engenharia de Computação",
          foto: "https://drive.google.com/open?id=1zXjVYES5bNZAbOxRcW1VcBSOYSXQnapO",
          githubLink: "https://github.com/caiogtoledo",
          hobby: "Tocar instrumentos, Praticar esportes",
          linguagens: "ReacJS, NodeJS, Flutter, Python, C",
          linkedinLink: "https://www.linkedin.com/in/caio-toledo/",
          name: "Caio Toledo",
          nascimento: "2001-11-02 00:00:00",
        },
        {
          ano: "4º",
          area: "RH, Diretoria",
          curso: "Engenharia de Computação",
          foto: "https://drive.google.com/open?id=1gzrfPy_ceg87ERTywwFEI37nysC-avd6",
          githubLink: "https://github.com/DanielBranquinho",
          hobby: "Jogar, ler, tocar cajón",
          linguagens: "Backend geral, Flutter, Tableau, tecnologias BI",
          linkedinLink: "https://www.linkedin.com/in/danielbranquinho/",
          name: "Daniel Branquinho Gomes",
          nascimento: "1996-06-02 00:00:00",
        },
        {
          ano: "4º",
          area: "Frontend",
          curso: "Engenharia de Computação",
          foto: "https://drive.google.com/open?id=1ll4wWzPCy5w5SD_U6XNEcqjkIP5ELHFG",
          githubLink: "https://github.com/Felipe-16",
          hobby: "Jogar Valorant",
          linguagens: "Flutter, python, SQL, Javascript, vue.js",
          linkedinLink:
            "https://www.linkedin.com/in/felipe-ros-pegini-engenheiro-computacao",
          name: "Felipe Ros Pegini ",
          nascimento: "1999-06-16 00:00:00",
        },
        {
          ano: "5º",
          area: "Frontend, Gerência de Projetos, Diretor de projetos, tech leader e dev front",
          curso: "Engenharia de Computação",
          foto: "https://drive.google.com/open?id=15oPulb5Z9RoCfC6ROOTKPhfh-fOwguXd",
          githubLink: "https://github.com/GabrielGodoy01",
          hobby: "Jogos e música",
          linguagens: "Flutter, Java, SQL, Angular, Node.js",
          linkedinLink: "https://www.linkedin.com/in/gabrielgbraz/",
          name: "Gabriel de Godoy Braz (Guerreiro)",
          nascimento: "1999-12-28 00:00:00",
        },
        {
          ano: "5º",
          area: "Frontend, Backend, DevOps, Diretoria",
          curso: "Engenharia de Computação",
          foto: "https://drive.google.com/open?id=13epZ3OIVFTK-ZTrOKURe75SaNu8mXQcJ",
          githubLink: "https://github.com/hectorguerrini",
          hobby: "Rugby, Programar, Beber",
          linguagens: "Flutter, Angular, Python, C#, Typescript ",
          linkedinLink:
            "https://www.linkedin.com/in/hector-guerrini-herrera-b08007116/",
          name: "Hector Guerrini Herrera",
          nascimento: "1997-04-07 00:00:00",
        },
        {
          ano: "2º",
          area: "Backend",
          curso: "Engenharia de Computação",
          foto: "https://drive.google.com/open?id=15XWC5Lxzc9ae7DAFFhQ7Nhw0B-MxyzSd",
          githubLink: "https://github.com/JoaoVitorBranco",
          hobby: "Jogar/ jogar tênis de mesa",
          linguagens: "Python",
          linkedinLink:
            "https://www.linkedin.com/in/jo%C3%A3o-vitor-choueri-branco-a756ab209",
          name: "João Vitor Choueri Branco ",
          nascimento: "2002-10-10 00:00:00",
        },
        {
          ano: "4º",
          area: "Backend",
          curso: "Engenharia de Computação",
          foto: "https://drive.google.com/open?id=1eOFGvzRJAP5o6NhtQv7yhxFgz4OW2Ds_",
          githubLink: "https://github.com/leonardozollner",
          hobby: "Viajar",
          linguagens: "",
          linkedinLink:
            "https://www.linkedin.com/in/leonardo-zollner-2b35571a9/",
          name: "Leonardo Zollner ",
          nascimento: "1999-12-03 00:00:00",
        },
        {
          ano: "4º",
          area: "DevOps",
          curso: "Engenharia de Computação",
          foto: "https://drive.google.com/open?id=1aJGhcLENKmrOuCBglYrquIyZCxmFo6hV",
          githubLink: "https://github.com/MatheusNakai",
          hobby: "Livros",
          linguagens: "",
          linkedinLink: "https://www.linkedin.com/in/matheus-nakai-36051a182/",
          name: "Matheus Nakai",
          nascimento: "1998-10-23 00:00:00",
        },
        {
          ano: "2º",
          area: "UX / UI, Comunicação",
          curso: "Engenharia de Computação",
          foto: "https://drive.google.com/open?id=1XhiYRZFWgG8OkCwykBOGl6Sqxq_OMeTo",
          githubLink: "https://github.com/Michelle-Hmzk",
          hobby: "Tirar fotos.",
          linguagens: "",
          linkedinLink: "https://www.linkedin.com/in/michelle-hmzk/",
          name: "Michelle Mitie Hamazaki",
          nascimento: "2001-08-22 00:00:00",
        },
        {
          ano: "5º",
          area: "Backend",
          curso: "Engenharia de Computação",
          foto: "https://drive.google.com/open?id=13hK4mNxUkC9TtFIsBJL-NeXPA-trN2Qf",
          githubLink: "https://github.com/goodguyplayer",
          hobby:
            "Estudar segurança digital, planejar projetos e códigos, expandir conhecimento em direção a computação e relacionados",
          linguagens: "Python, Pytest, Java, C",
          linkedinLink:
            "https://www.linkedin.com/in/nathan-brito-da-silva-b61343184/",
          name: "Nathan Brito da Silva",
          nascimento: "1997-11-04 00:00:00",
        },
        {
          ano: "4º",
          area: "Backend",
          curso: "Engenharia de Computação",
          foto: "https://drive.google.com/open?id=15qw4Ps9QeJ4VEFOPmNZh5KKfRVg8aGTs",
          githubLink: "https://github.com/Renan-Reschke",
          hobby: "Empinar pipa e jogar Counter Strike",
          linguagens: "Python, C, C#, Java, FastAPI, Oracle, SQL Server",
          linkedinLink: "https://www.linkedin.com/in/renan-reschke-606329198/",
          name: "Renan Scheidt Reschke",
          nascimento: "2001-02-04 00:00:00",
        },
      ],
    },
    {
      foto: require("./assets/smilesSite.png"),
      name: "Site Smile",
      frontend: "Flutter",
      backend: "NodeJS",
      link: "https://github.com/Maua-Dev/smile_front",
      membros: [
        {
          ano: "3º",
          area: "Frontend, Gerência de Projetos",
          curso: "Engenharia de Computação",
          foto: "https://drive.google.com/open?id=1zXjVYES5bNZAbOxRcW1VcBSOYSXQnapO",
          githubLink: "https://github.com/caiogtoledo",
          hobby: "Tocar instrumentos, Praticar esportes",
          linguagens: "ReacJS, NodeJS, Flutter, Python, C",
          linkedinLink: "https://www.linkedin.com/in/caio-toledo/",
          name: "Caio Toledo",
          nascimento: "2001-11-02 00:00:00",
        },
        {
          ano: "5º",
          area: "Diretoria",
          curso: "Engenharia de Computação",
          foto: "https://drive.google.com/open?id=15XDejAfL35YN8yr-8eJhf5dSn4mfF2JV",
          githubLink: "https://github.com/Daniel-Xavier",
          hobby: "jogar video game",
          linguagens: "Python",
          linkedinLink: "https://www.linkedin.com/in/daniel-xavier-134378165/",
          name: "Daniel Xavier",
          nascimento: "1998-09-04 00:00:00",
        },
        {
          ano: "5º",
          area: "Frontend",
          curso: "Engenharia de Computação",
          foto: "https://drive.google.com/open?id=1K06EjXps-E3jC9CY_n0LcdMsLYwwptsa",
          githubLink: "https://github.com/FePaganini",
          hobby: "Assistir séries, jogar no PC",
          linguagens: "Javascript, Html, CSS, Java, React",
          linkedinLink: "",
          name: "Felipe Paganini",
          nascimento: "2000-05-06 00:00:00",
        },
        {
          ano: "5º",
          area: "Frontend, Gerência de Projetos, Diretor de projetos, tech leader e dev front",
          curso: "Engenharia de Computação",
          foto: "https://drive.google.com/open?id=15oPulb5Z9RoCfC6ROOTKPhfh-fOwguXd",
          githubLink: "https://github.com/GabrielGodoy01",
          hobby: "Jogos e música",
          linguagens: "Flutter, Java, SQL, Angular, Node.js",
          linkedinLink: "https://www.linkedin.com/in/gabrielgbraz/",
          name: "Gabriel de Godoy Braz (Guerreiro)",
          nascimento: "1999-12-28 00:00:00",
        },
        {
          ano: "4º",
          area: "Frontend",
          curso: "Engenharia de Produção",
          foto: "https://drive.google.com/open?id=1ByR5hT1hvfThZj43FwYMKl2LshQcpJV5",
          githubLink: "",
          hobby: "Fazer yoga e assistir filmes e séries ",
          linguagens: "",
          linkedinLink: "www.linkedin.com/in/letícia-magalhães2505",
          name: "Leticia Magalhães",
          nascimento: "1999-05-25 00:00:00",
        },
        {
          ano: "5º",
          area: "Backend, UX / UI",
          curso: "Engenharia de Computação",
          foto: "https://drive.google.com/open?id=11PzLLssFRaSP0-fdV6u2jitzA7lbL6Ok",
          githubLink: "https://github.com/YagoBattaggia",
          hobby: "Programação e Jogos",
          linguagens: "Javascript, NodeJs, Java, Python, C",
          linkedinLink: "https://www.linkedin.com/in/yago-battaggia-01035a148/",
          name: "Yago Garcia Battaggia",
          nascimento: "2000-05-07 00:00:00",
        },
      ],
    },
    {
      foto: require("./assets/portfolioSite.png"),
      name: "Portfólio Dev. Community",
      frontend: "React JS",
      backend: "Não possui",
      link: "https://github.com/Maua-Dev/Site-portfolio",
      membros: [
        {
          ano: "3º",
          area: "Frontend",
          curso: "Engenharia de Controle e Automação",
          foto: "https://drive.google.com/open?id=1Eh8wMMFBFcdPAngx-aSNariCk7gMhF6e",
          githubLink: "https://github.com/KurekCaio",
          hobby: "Esportes",
          linguagens: "HTML, CSS, JS, React",
          linkedinLink: "www.linkedin.com/in/caio-kurek-6489bb1ab",
          name: "Caio Kurek Marques Manuel",
          nascimento: "2002-04-06 00:00:00",
        },
        {
          ano: "3º",
          area: "Frontend, Gerência de Projetos",
          curso: "Engenharia de Computação",
          foto: "https://drive.google.com/open?id=1zXjVYES5bNZAbOxRcW1VcBSOYSXQnapO",
          githubLink: "https://github.com/caiogtoledo",
          hobby: "Tocar instrumentos, Praticar esportes",
          linguagens: "ReacJS, NodeJS, Flutter, Python, C",
          linkedinLink: "https://www.linkedin.com/in/caio-toledo/",
          name: "Caio Toledo",
          nascimento: "2001-11-02 00:00:00",
        },
        {
          ano: "3º",
          area: "Frontend",
          curso: "Engenharia de Controle e Automação",
          foto: "https://drive.google.com/open?id=1jX_K_GKaUVBPib1nP0HJF-b8nLHj27JG",
          githubLink: "https://github.com/viso4res",
          hobby: "Carros",
          linguagens: "HTML, CSS, JS e React",
          linkedinLink:
            "https://www.linkedin.com/in/vinicius-alves-soares-4037581ab/",
          name: "Vinicius Alves Soares",
          nascimento: "2000-12-05 00:00:00",
        },
        {
          ano: "2º",
          area: "Frontend, Comunicação",
          curso: "Engenharia de Computação",
          foto: "https://drive.google.com/open?id=175FTKhjgzyveOCfWX-7DspFZiZx2v3j0",
          githubLink: "https://github.com/VgsStudio",
          hobby: "Jogar Terraria e decorar bandeiras de países.",
          linguagens: "Python, Javascript, ReactJS, HTML, CSS",
          linkedinLink: "https://www.linkedin.com/in/vitor-soller/",
          name: "Vitor Soller",
          nascimento: "2002-11-08 00:00:00",
        },
      ],
    },
  ],
};

export default data;
