const data = {
  projects: [
    {
      foto: require("./assets/mauaFood.png"),
      name: "MauáFood",
      frontend: "Flutter",
      backend: "Python",
      link: "https://github.com/Maua-Dev/mauafood_front.git",

      membros: [
        {
          name: "Bruno Vilardi Bueno",
          foto: "https://drive.google.com/uc?id=1IKIyM5G5jivSx0y7YLnZ-XWD-QvnQ5AC",
          ra: "19.00331-5",
          nascimento: "1/15/2001",
          email: "bvilardi.devmaua@gmail.com",
          area: "DEV;Infra\u00a0;Diretoria\u00a0;",
          curso: "Engenharia de Computa\u00e7\u00e3o\u00a0",
          ano: "4\u00b0",
          linkedinLink:
            "https://www.linkedin.com/in/bruno-vilardi-bueno-8b054a187",
          githubLink: "https://github.com/Brvilardi",
        },
        {
          name: "Caio Montes Correia",
          foto: "https://drive.google.com/uc?id=1zMliG4UOgT8LrUg4XyPJCvPjHAcaAqC0",
          ra: "21.00931-7",
          nascimento: "8/20/2003",
          email: "ccorreia.devmaua@gmail.com",
          area: "Diretoria\u00a0;DEV;",
          curso: "Engenharia de Computa\u00e7\u00e3o\u00a0",
          ano: "2",
          linkedinLink: "https://www.linkedin.com/in/caiomontes/",
          githubLink: "https://github.com/caiomc03",
        },
        {
          name: "Gabriel de Godoy Braz",
          foto: "https://drive.google.com/uc?id=15oPulb5Z9RoCfC6ROOTKPhfh-fOwguXd",
          ra: "17.00163-3",
          nascimento: "12/28/1999",
          email: "gbraz.devmaua@gmail.com",
          area: "Diretoria\u00a0;DEV;",
          curso: "Engenharia de Computa\u00e7\u00e3o\u00a0",
          ano: "5\u00b0",
          linkedinLink: "https://www.linkedin.com/in/gabrielgbraz/",
          githubLink: "https://github.com/GabrielGodoy01",
        },
        {
          name: "Andr\u00e9 Monteiro de Freitas",
          foto: "https://drive.google.com/uc?id=1ywHTbMDvWB7T94w3kMqz_LKhYZnClXGo",
          ra: "21.00288-6",
          nascimento: "9/7/2002",
          email: "afreitas.devmaua@gmail.com",
          area: "DEV;",
          curso: "Ci\u00eancias da Computa\u00e7\u00e3o\u00a0",
          ano: "1\u00b0",
          linkedinLink: "https://www.linkedin.com/in/andr%C3%A9-m-47b916209/",
          githubLink: "https://github.com/AndreMdeFreitas",
        },
        {
          name: "Lucas Milani Thomsen Galhardo",
          foto: "https://drive.google.com/uc?id=1n_pRqvVYVuxzCsAkgihqqzh3I5jnZUrx",
          ra: "22.00818-7",
          nascimento: "6/10/2003",
          email: "lgalhardo.devmaua@gmail.com",
          area: "Seguran\u00e7a\u00a0;DEV;",
          curso: "Engenharia de Computa\u00e7\u00e3o\u00a0",
          ano: "1\u00b0",
          linkedinLink: "linkedin.com/in/lucasmtgalhardo/",
          githubLink: "github.com/LucasKiller",
        },
        {
          name: "Rodrigo Diana Siqueira",
          foto: "https://drive.google.com/uc?id=1ga48wir5qy_-SRUOWu4nJlr4aV_3vzH4",
          ra: "22.00680-0",
          nascimento: "10/10/2003",
          email: "rsiqueira.devmaua@gmail.com",
          area: "DEV;",
          curso: "Ci\u00eancias da Computa\u00e7\u00e3o\u00a0",
          ano: "1\u00b0",
          linkedinLink:
            "https://www.linkedin.com/in/rodrigo-siqueira-76955822b",
          githubLink: "https://github.com/Rodrigosiq03",
        },
        {
          name: "Rodrigo Reis Monasterios Morales",
          foto: "https://drive.google.com/uc?id=19aIeSBpixSpiYjN7mv-pM_FlUbnVL9zi",
          ra: "22.01432-2",
          nascimento: "6/15/2004",
          email: "rmorales.devmaua@gmail.com",
          area: "DEV;",
          curso: "Engenharia de Computa\u00e7\u00e3o\u00a0",
          ano: "1\u00b0",
          linkedinLink: "",
          githubLink: "https://github.com/RodrigoM2004",
        },
        {
          name: "Daniel Capuzzo Veiga",
          foto: "https://drive.google.com/uc?id=1TA1zmKMd3oGx9599Zn9kkScZ1h6YTRWe",
          ra: "22.00122-0",
          nascimento: "9/13/2022",
          email: "dcapuzzo.devmaua@gmail.com",
          area: "UX/UI;",
          curso: "Design\u00a0",
          ano: "1\u00b0",
          linkedinLink: "https://www.linkedin.com/in/daniel-capuzzo-363a0024a/",
          githubLink: "",
        },
        {
          name: "Fernando Andrade Rodrigues",
          foto: "https://drive.google.com/uc?id=181f7YUoUt3M2WT0KFU5NldgBYCwTYuyp&authuser=2",
          ra: "22.00968-0",
          nascimento: "4/6/2004",
          email: "fandrade.devmaua@gmail.com",
          area: "PO;",
          curso: "Engenharia de Produ\u00e7\u00e3o\u00a0",
          ano: "1\u00b0",
          linkedinLink:
            "https://www.linkedin.com/in/fernando-andrade-rodrigues-3b424823b",
          githubLink: "https://github.com/FernandoAndrade-devmaua",
        },
        {
          name: "Daniel Victor Santos Silva",
          foto: "",
          ra: "21.00794-",
          nascimento: "8/22/2002",
          email: "dvictor.devmaua@gmail.com",
          area: "Data Science\u00a0;",
          curso: "Engenharia de Controle e Automa\u00e7\u00e3o\u00a0",
          ano: "2",
          linkedinLink:
            "https://www.linkedin.com/in/daniel-victor-santos-silva-a92985190/",
          githubLink: "https://github.com/Danivictorsilva",
        },
      ],
    },
    {
      foto: require("./assets/smileSite.png"),
      name: "Site Smile",
      frontend: "Flutter",
      backend: "Python",
      link: "https://github.com/Maua-Dev/smile_front",

      membros: [
        {
          name: "Bruno Vilardi Bueno",
          foto: "https://drive.google.com/uc?id=1IKIyM5G5jivSx0y7YLnZ-XWD-QvnQ5AC",
          ra: "19.00331-5",
          nascimento: "1/15/2001",
          email: "bvilardi.devmaua@gmail.com",
          area: "DEV;Infra\u00a0;Diretoria\u00a0;",
          curso: "Engenharia de Computa\u00e7\u00e3o\u00a0",
          ano: "4\u00b0",
          linkedinLink:
            "https://www.linkedin.com/in/bruno-vilardi-bueno-8b054a187",
          githubLink: "https://github.com/Brvilardi",
        },
        {
          name: "Caio Bartolozzi Bastos Godoy de Toledo",
          foto: "https://drive.google.com/uc?id=1zXjVYES5bNZAbOxRcW1VcBSOYSXQnapO",
          ra: "20.01430-9",
          nascimento: "11/2/2001",
          email: "ctoledo.devmaua@gmail.com",
          area: "Diretoria\u00a0;",
          curso: "Engenharia de Computa\u00e7\u00e3o\u00a0",
          ano: "3\u00b0",
          linkedinLink: "https://www.linkedin.com/in/caio-toledo",
          githubLink: "https://github.com/caiogtoledo",
        },
        {
          name: "Gabriel de Godoy Braz",
          foto: "https://drive.google.com/uc?id=15oPulb5Z9RoCfC6ROOTKPhfh-fOwguXd",
          ra: "17.00163-3",
          nascimento: "12/28/1999",
          email: "gbraz.devmaua@gmail.com",
          area: "Diretoria\u00a0;DEV;",
          curso: "Engenharia de Computa\u00e7\u00e3o\u00a0",
          ano: "5\u00b0",
          linkedinLink: "https://www.linkedin.com/in/gabrielgbraz/",
          githubLink: "https://github.com/GabrielGodoy01",
        },
        {
          name: "Hector Guerrini Herrera",
          foto: "https://drive.google.com/uc?id=13epZ3OIVFTK-ZTrOKURe75SaNu8mXQcJ",
          ra: "15.01310-3",
          nascimento: "4/7/1997",
          email: "hguerrini.devmaua@gmail.com",
          area: "Diretoria\u00a0;",
          curso: "Engenharia de Computa\u00e7\u00e3o\u00a0",
          ano: "5\u00b0",
          linkedinLink:
            "https://www.linkedin.com/in/hector-guerrini-herrera-b08007116/",
          githubLink: "https://github.com/hectorguerrini",
        },
        {
          name: "Breno Amorim Roman",
          foto: "https://drive.google.com/uc?id=1GhKkimYORnbyLswf5ldf8D1rDDaIwZKV",
          ra: "20.00395-0",
          nascimento: "11/11/2001",
          email: "bamorim.devmaua@gmail.com",
          area: "DEV;",
          curso: "Engenharia de Computa\u00e7\u00e3o\u00a0",
          ano: "2",
          linkedinLink:
            "https://www.linkedin.com/in/breno-amorim-roman-15897997/",
          githubLink: "https://gitHub.com/AmorimBreno",
        },
        {
          name: "Daniel Djinishian de Briquez",
          foto: "https://drive.google.com/uc?id=1OApTviIKowCNdsQOppKHHTX-XaiXJjJi",
          ra: "22.00251-0",
          nascimento: "5/23/2001",
          email: "dbriquez.devmaua@gmail.com",
          area: "DEV;",
          curso: "Ci\u00eancias da Computa\u00e7\u00e3o\u00a0",
          ano: "1\u00b0",
          linkedinLink: "https://www.linkedin.com/in/daniel-briquez-306289232/",
          githubLink: "https://github.com/Briqz23/",
        },
        {
          name: "Enrico Mota Santarelli",
          foto: "https://drive.google.com/uc?id=1TvDXt3DYNEWUVUVcZiigXE9zC_HpBdtS&authuser=2",
          ra: "22.00370-3",
          nascimento: "7/23/2003",
          email: "esantarelli.devmaua@gmail.com",
          area: "DEV;",
          curso: "Engenharia de Computa\u00e7\u00e3o\u00a0",
          ano: "1\u00b0",
          linkedinLink:
            "https://www.linkedin.com/in/enrico-santarelli-b50054236/",
          githubLink: "https://github.com/EnricoSantarelli",
        },
        {
          name: "Lucas Romanato de Oliveira",
          foto: "https://drive.google.com/uc?id=1OqUA-LcmOCX5VsIUpxlv5yhsSa2kCUyN",
          ra: "20.00313-7",
          nascimento: "9/4/2001",
          email: "lromanato.devmaua@gmail.com",
          area: "DEV;",
          curso: "Engenharia de Computa\u00e7\u00e3o\u00a0",
          ano: "3\u00b0",
          linkedinLink:
            "https://www.linkedin.com/in/lucas-romanato-de-oliveira/",
          githubLink: "https://github.com/LucasRomanato0",
        },
        {
          name: "Raphael Marchetti Calciolari",
          foto: "",
          ra: "19.00828-7",
          nascimento: "9/13/2000",
          email: "rmarchetti.devmaua@gmail.com",
          area: "Infra\u00a0;",
          curso: "Engenharia de Computa\u00e7\u00e3o\u00a0",
          ano: "4\u00b0",
          linkedinLink:
            "https://www.linkedin.com/mwlite/in/raphael-marchetti-calciolari-8555631a7",
          githubLink: "https://github.com/raphazik4",
        },
        {
          name: "Victor Cecche Pregnolatto",
          foto: "https://drive.google.com/uc?id=18OF7sI2ZnYT98PmJEvuWH4yYZW3RlmKx",
          ra: "21.00928-7",
          nascimento: "10/21/2002",
          email: "Vcecche.devmaua@gmail.com",
          area: "Infra\u00a0;Seguran\u00e7a\u00a0;",
          curso: "Engenharia de Computa\u00e7\u00e3o\u00a0",
          ano: "2",
          linkedinLink:
            "https://www.linkedin.com/in/victor-cecche-pregnolatto-0b027a1b9",
          githubLink: "https://github.com/Djopos",
        },
        {
          name: "Fernando Andrade Rodrigues",
          foto: "https://drive.google.com/uc?id=181f7YUoUt3M2WT0KFU5NldgBYCwTYuyp&authuser=2",
          ra: "22.00968-0",
          nascimento: "4/6/2004",
          email: "fandrade.devmaua@gmail.com",
          area: "PO;",
          curso: "Engenharia de Produ\u00e7\u00e3o\u00a0",
          ano: "1\u00b0",
          linkedinLink:
            "https://www.linkedin.com/in/fernando-andrade-rodrigues-3b424823b",
          githubLink: "https://github.com/FernandoAndrade-devmaua",
        },
      ],
    },
    {
      foto: require("./assets/portfolioSite.png"),
      name: "Portfólio Dev. Community",
      frontend: "React JS",
      backend: "Python",
      link: "https://github.com/Maua-Dev/Site-portfolio",

      membros: [
        {
          name: "Bruno Vilardi Bueno",
          foto: "https://drive.google.com/uc?id=1IKIyM5G5jivSx0y7YLnZ-XWD-QvnQ5AC",
          ra: "19.00331-5",
          nascimento: "1/15/2001",
          email: "bvilardi.devmaua@gmail.com",
          area: "DEV;Infra\u00a0;Diretoria\u00a0;",
          curso: "Engenharia de Computa\u00e7\u00e3o\u00a0",
          ano: "4\u00b0",
          linkedinLink:
            "https://www.linkedin.com/in/bruno-vilardi-bueno-8b054a187",
          githubLink: "https://github.com/Brvilardi",
        },
        {
          name: "Caio Bartolozzi Bastos Godoy de Toledo",
          foto: "https://drive.google.com/uc?id=1zXjVYES5bNZAbOxRcW1VcBSOYSXQnapO",
          ra: "20.01430-9",
          nascimento: "11/2/2001",
          email: "ctoledo.devmaua@gmail.com",
          area: "Diretoria\u00a0;",
          curso: "Engenharia de Computa\u00e7\u00e3o\u00a0",
          ano: "3\u00b0",
          linkedinLink: "https://www.linkedin.com/in/caio-toledo",
          githubLink: "https://github.com/caiogtoledo",
        },
        {
          name: "Bruno Augusto Lopes Fevereiro",
          foto: "https://drive.google.com/uc?id=1YR_T2cRHMl8QrBxfAGLW4dbfK4pfw6Uc",
          ra: "20.02194-0",
          nascimento: "7/10/2002",
          email: "bfevereiro.devmaua@gmail.com",
          area: "DEV;",
          curso: "Engenharia de Computa\u00e7\u00e3o\u00a0",
          ano: "2",
          linkedinLink: "https://www.linkedin.com/in/bruno-fevereiro/",
          githubLink: "https://github.com/BRUNO-FEVE",
        },
        {
          name: "Enzo Yuji Sakamoto",
          foto: "https://drive.google.com/uc?id=1s3R15WhQ1lN-jRfg-wDQF7MeWgtkmmu1&authuser=2",
          ra: "21.00210-0",
          nascimento: "7/20/2002",
          email: "esakamoto.devmaua@gmail.com",
          area: "DEV;",
          curso: "Engenharia de Computa\u00e7\u00e3o\u00a0",
          ano: "2",
          linkedinLink: "https://www.linkedin.com/in/enzosakamoto",
          githubLink: "https://github.com/enzosakamoto",
        },
        {
          name: "Rafael Rubio Carnes",
          foto: "https://drive.google.com/uc?id=17jnv-K_GtfWpAx95Vun_0fr3wIceJTRw",
          ra: "20.00611-0",
          nascimento: "5/25/2002",
          email: "rrubio.devmaua@gmail.com",
          area: "DEV;",
          curso: "Engenharia de Computa\u00e7\u00e3o\u00a0",
          ano: "2",
          linkedinLink:
            "https://www.linkedin.com/in/rafael-rubio-carnes-b2561b212/",
          githubLink: "https://github.com/Rubiozito",
        },
        {
          name: "Vitor Guir\u00e3o Soller",
          foto: "https://drive.google.com/uc?id=175FTKhjgzyveOCfWX-7DspFZiZx2v3j0",
          ra: "21.01444-2",
          nascimento: "11/8/2022",
          email: "vsoller.devmaua@gmail.com",
          area: "DEV;",
          curso: "Engenharia de Computa\u00e7\u00e3o\u00a0",
          ano: "2",
          linkedinLink: "https://www.linkedin.com/in/vitor-soller/",
          githubLink: "https://github.com/VgsStudio",
        },
        {
          name: "Lucas Fernandes Rodrigues Mendes",
          foto: "",
          ra: "20.02175-5",
          nascimento: "1/17/2001",
          email: "lfernandes.devmaua@gmail.com",
          area: "Comunica\u00e7\u00e3o\u00a0;UX/UI;",
          curso: "Design\u00a0",
          ano: "1\u00b0",
          linkedinLink: "",
          githubLink: "",
        },
        {
          name: "Dimitri Zenaro Bastos de Oliveira",
          foto: "https://drive.google.com/uc?id=1z69nd-_gZKN3C32KRVRea3IZbPwkJxyg",
          ra: "22.00820-9",
          nascimento: "12/21/2003",
          email: "dimizen.devmaua@gmail.com",
          area: "Data Science\u00a0;",
          curso: "Ci\u00eancias da Computa\u00e7\u00e3o\u00a0",
          ano: "1\u00b0",
          linkedinLink: "https://www.linkedin.com/in/dimitri-zenaro-1a8279213/",
          githubLink: "http://github.com/Diimy",
        },
        {
          name: "Luigi Guimar\u00e3es Trevisan",
          foto: "https://drive.google.com/uc?id=1U1Vh4qH1GbSRKYVXdYJzjCPmKme-BnAe",
          ra: "22.01102-",
          nascimento: "12/17/2004",
          email: "ltrevisan.devmaua@gmail.com",
          area: "Data Science\u00a0;",
          curso: "Ci\u00eancias da Computa\u00e7\u00e3o\u00a0",
          ano: "1\u00b0",
          linkedinLink: "https://www.linkedin.com/in/luigi-trevisan/",
          githubLink: "https://github.com/LuigiTrevisan",
        },
      ],
    },
    {
      foto: require("./assets/hackaton.jpeg"),
      name: "Hackathon",
      frontend: "Flutter",
      backend: "",
      link: "",

      membros: [
        {
          name: "Bruno Vilardi Bueno",
          foto: "https://drive.google.com/uc?id=1IKIyM5G5jivSx0y7YLnZ-XWD-QvnQ5AC",
          ra: "19.00331-5",
          nascimento: "1/15/2001",
          email: "bvilardi.devmaua@gmail.com",
          area: "DEV;Infra\u00a0;Diretoria\u00a0;",
          curso: "Engenharia de Computa\u00e7\u00e3o\u00a0",
          ano: "4\u00b0",
          linkedinLink:
            "https://www.linkedin.com/in/bruno-vilardi-bueno-8b054a187",
          githubLink: "https://github.com/Brvilardi",
        },
        {
          name: "Caio Montes Correia",
          foto: "https://drive.google.com/uc?id=1zMliG4UOgT8LrUg4XyPJCvPjHAcaAqC0",
          ra: "21.00931-7",
          nascimento: "8/20/2003",
          email: "ccorreia.devmaua@gmail.com",
          area: "Diretoria\u00a0;DEV;",
          curso: "Engenharia de Computa\u00e7\u00e3o\u00a0",
          ano: "2",
          linkedinLink: "https://www.linkedin.com/in/caiomontes/",
          githubLink: "https://github.com/caiomc03",
        },
        {
          name: "Hector Guerrini Herrera",
          foto: "https://drive.google.com/uc?id=13epZ3OIVFTK-ZTrOKURe75SaNu8mXQcJ",
          ra: "15.01310-3",
          nascimento: "4/7/1997",
          email: "hguerrini.devmaua@gmail.com",
          area: "Diretoria\u00a0;",
          curso: "Engenharia de Computa\u00e7\u00e3o\u00a0",
          ano: "5\u00b0",
          linkedinLink:
            "https://www.linkedin.com/in/hector-guerrini-herrera-b08007116/",
          githubLink: "https://github.com/hectorguerrini",
        },
        {
          name: "Andr\u00e9 Monteiro de Freitas",
          foto: "https://drive.google.com/uc?id=1ywHTbMDvWB7T94w3kMqz_LKhYZnClXGo",
          ra: "21.00288-6",
          nascimento: "9/7/2002",
          email: "afreitas.devmaua@gmail.com",
          area: "DEV;",
          curso: "Ci\u00eancias da Computa\u00e7\u00e3o\u00a0",
          ano: "1\u00b0",
          linkedinLink: "https://www.linkedin.com/in/andr%C3%A9-m-47b916209/",
          githubLink: "https://github.com/AndreMdeFreitas",
        },
        {
          name: "Breno Amorim Roman",
          foto: "https://drive.google.com/uc?id=1GhKkimYORnbyLswf5ldf8D1rDDaIwZKV",
          ra: "20.00395-0",
          nascimento: "11/11/2001",
          email: "bamorim.devmaua@gmail.com",
          area: "DEV;",
          curso: "Engenharia de Computa\u00e7\u00e3o\u00a0",
          ano: "2",
          linkedinLink:
            "https://www.linkedin.com/in/breno-amorim-roman-15897997/",
          githubLink: "https://gitHub.com/AmorimBreno",
        },
        {
          name: "Bruno Augusto Lopes Fevereiro",
          foto: "https://drive.google.com/uc?id=1YR_T2cRHMl8QrBxfAGLW4dbfK4pfw6Uc",
          ra: "20.02194-0",
          nascimento: "7/10/2002",
          email: "bfevereiro.devmaua@gmail.com",
          area: "DEV;",
          curso: "Engenharia de Computa\u00e7\u00e3o\u00a0",
          ano: "2",
          linkedinLink: "https://www.linkedin.com/in/bruno-fevereiro/",
          githubLink: "https://github.com/BRUNO-FEVE",
        },
        {
          name: "Daniel Djinishian de Briquez",
          foto: "https://drive.google.com/uc?id=1OApTviIKowCNdsQOppKHHTX-XaiXJjJi",
          ra: "22.00251-0",
          nascimento: "5/23/2001",
          email: "dbriquez.devmaua@gmail.com",
          area: "DEV;",
          curso: "Ci\u00eancias da Computa\u00e7\u00e3o\u00a0",
          ano: "1\u00b0",
          linkedinLink: "https://www.linkedin.com/in/daniel-briquez-306289232/",
          githubLink: "https://github.com/Briqz23/",
        },
        {
          name: "Davi Fernandes Sim\u00f5es Soares",
          foto: "https://drive.google.com/uc?id=13w8Mt0_zhIueTlSXY2qw6yd0ZURFMbBT",
          ra: "20.01099-0",
          nascimento: "7/26/2002",
          email: "dsoares.devmaua@gmail.com",
          area: "DEV;",
          curso: "Engenharia de Computa\u00e7\u00e3o\u00a0",
          ano: "3\u00b0",
          linkedinLink:
            "https://www.linkedin.com/in/davi-fernandes-sim\u00f5es-soares-58299b1a8/",
          githubLink: "https://github.com/Davi-fsS",
        },
        {
          name: "Enrico Mota Santarelli",
          foto: "https://drive.google.com/uc?id=1TvDXt3DYNEWUVUVcZiigXE9zC_HpBdtS&authuser=2",
          ra: "22.00370-3",
          nascimento: "7/23/2003",
          email: "esantarelli.devmaua@gmail.com",
          area: "DEV;",
          curso: "Engenharia de Computa\u00e7\u00e3o\u00a0",
          ano: "1\u00b0",
          linkedinLink:
            "https://www.linkedin.com/in/enrico-santarelli-b50054236/",
          githubLink: "https://github.com/EnricoSantarelli",
        },
        {
          name: "Enzo Yuji Sakamoto",
          foto: "https://drive.google.com/uc?id=1s3R15WhQ1lN-jRfg-wDQF7MeWgtkmmu1&authuser=2",
          ra: "21.00210-0",
          nascimento: "7/20/2002",
          email: "esakamoto.devmaua@gmail.com",
          area: "DEV;",
          curso: "Engenharia de Computa\u00e7\u00e3o\u00a0",
          ano: "2",
          linkedinLink: "https://www.linkedin.com/in/enzosakamoto",
          githubLink: "https://github.com/enzosakamoto",
        },
        {
          name: "Jo\u00e3o Vitor Choueri Branco",
          foto: "https://drive.google.com/uc?id=15XWC5Lxzc9ae7DAFFhQ7Nhw0B-MxyzSd",
          ra: "21.01075-7",
          nascimento: "10/10/2002",
          email: "jbranco.devmaua@gmail.com",
          area: "DEV;",
          curso: "Engenharia de Computa\u00e7\u00e3o\u00a0",
          ano: "2",
          linkedinLink:
            "https://www.linkedin.com/in/jo%C3%A3o-vitor-choueri-branco-a756ab209",
          githubLink: "https://github.com/JoaoVitorBranco",
        },
        {
          name: "Lucas Duez Verzaro dos Santos",
          foto: "https://drive.google.com/uc?id=1bI4y08CNip0AVPAuT_Igh3d7JJllwtnM&authuser=2",
          ra: "21.00306-8",
          nascimento: "1/10/2002",
          email: "lduez.devmaua@gmail.com",
          area: "DEV;",
          curso: "Ci\u00eancias da Computa\u00e7\u00e3o\u00a0",
          ano: "1\u00b0",
          linkedinLink:
            "https://www.linkedin.com/in/lucas-duez-verzaro-463895208/",
          githubLink: "https://github.com/Lucasdvs10",
        },
        {
          name: "Lucas Romanato de Oliveira",
          foto: "https://drive.google.com/uc?id=1OqUA-LcmOCX5VsIUpxlv5yhsSa2kCUyN",
          ra: "20.00313-7",
          nascimento: "9/4/2001",
          email: "lromanato.devmaua@gmail.com",
          area: "DEV;",
          curso: "Engenharia de Computa\u00e7\u00e3o\u00a0",
          ano: "3\u00b0",
          linkedinLink:
            "https://www.linkedin.com/in/lucas-romanato-de-oliveira/",
          githubLink: "https://github.com/LucasRomanato0",
        },
        {
          name: "Rafael Rubio Carnes",
          foto: "https://drive.google.com/uc?id=17jnv-K_GtfWpAx95Vun_0fr3wIceJTRw",
          ra: "20.00611-0",
          nascimento: "5/25/2002",
          email: "rrubio.devmaua@gmail.com",
          area: "DEV;",
          curso: "Engenharia de Computa\u00e7\u00e3o\u00a0",
          ano: "2",
          linkedinLink:
            "https://www.linkedin.com/in/rafael-rubio-carnes-b2561b212/",
          githubLink: "https://github.com/Rubiozito",
        },
        {
          name: "Rodrigo Diana Siqueira",
          foto: "https://drive.google.com/uc?id=1ga48wir5qy_-SRUOWu4nJlr4aV_3vzH4",
          ra: "22.00680-0",
          nascimento: "10/10/2003",
          email: "rsiqueira.devmaua@gmail.com",
          area: "DEV;",
          curso: "Ci\u00eancias da Computa\u00e7\u00e3o\u00a0",
          ano: "1\u00b0",
          linkedinLink:
            "https://www.linkedin.com/in/rodrigo-siqueira-76955822b",
          githubLink: "https://github.com/Rodrigosiq03",
        },
        {
          name: "Rodrigo Reis Monasterios Morales",
          foto: "https://drive.google.com/uc?id=19aIeSBpixSpiYjN7mv-pM_FlUbnVL9zi",
          ra: "22.01432-2",
          nascimento: "6/15/2004",
          email: "rmorales.devmaua@gmail.com",
          area: "DEV;",
          curso: "Engenharia de Computa\u00e7\u00e3o\u00a0",
          ano: "1\u00b0",
          linkedinLink: "",
          githubLink: "https://github.com/RodrigoM2004",
        },
        {
          name: "Vitor Guir\u00e3o Soller",
          foto: "https://drive.google.com/uc?id=175FTKhjgzyveOCfWX-7DspFZiZx2v3j0",
          ra: "21.01444-2",
          nascimento: "11/8/2022",
          email: "vsoller.devmaua@gmail.com",
          area: "DEV;",
          curso: "Engenharia de Computa\u00e7\u00e3o\u00a0",
          ano: "2",
          linkedinLink: "https://www.linkedin.com/in/vitor-soller/",
          githubLink: "https://github.com/VgsStudio",
        },
        {
          name: "Victor Cecche Pregnolatto",
          foto: "https://drive.google.com/uc?id=18OF7sI2ZnYT98PmJEvuWH4yYZW3RlmKx",
          ra: "21.00928-7",
          nascimento: "10/21/2002",
          email: "Vcecche.devmaua@gmail.com",
          area: "Infra\u00a0;Seguran\u00e7a\u00a0;",
          curso: "Engenharia de Computa\u00e7\u00e3o\u00a0",
          ano: "2",
          linkedinLink:
            "https://www.linkedin.com/in/victor-cecche-pregnolatto-0b027a1b9",
          githubLink: "https://github.com/Djopos",
        },
        {
          name: "Daniel Capuzzo Veiga",
          foto: "https://drive.google.com/uc?id=1TA1zmKMd3oGx9599Zn9kkScZ1h6YTRWe",
          ra: "22.00122-0",
          nascimento: "9/13/2022",
          email: "dcapuzzo.devmaua@gmail.com",
          area: "UX/UI;",
          curso: "Design\u00a0",
          ano: "1\u00b0",
          linkedinLink: "https://www.linkedin.com/in/daniel-capuzzo-363a0024a/",
          githubLink: "",
        },
        {
          name: "Fernando Andrade Rodrigues",
          foto: "https://drive.google.com/uc?id=181f7YUoUt3M2WT0KFU5NldgBYCwTYuyp&authuser=2",
          ra: "22.00968-0",
          nascimento: "4/6/2004",
          email: "fandrade.devmaua@gmail.com",
          area: "PO;",
          curso: "Engenharia de Produ\u00e7\u00e3o\u00a0",
          ano: "1\u00b0",
          linkedinLink:
            "https://www.linkedin.com/in/fernando-andrade-rodrigues-3b424823b",
          githubLink: "https://github.com/FernandoAndrade-devmaua",
        },
        {
          name: "Daniel Victor Santos Silva",
          foto: "",
          ra: "21.00794-",
          nascimento: "8/22/2002",
          email: "dvictor.devmaua@gmail.com",
          area: "Data Science\u00a0;",
          curso: "Engenharia de Controle e Automa\u00e7\u00e3o\u00a0",
          ano: "2",
          linkedinLink:
            "https://www.linkedin.com/in/daniel-victor-santos-silva-a92985190/",
          githubLink: "https://github.com/Danivictorsilva",
        },
        {
          name: "Dimitri Zenaro Bastos de Oliveira",
          foto: "https://drive.google.com/uc?id=1z69nd-_gZKN3C32KRVRea3IZbPwkJxyg",
          ra: "22.00820-9",
          nascimento: "12/21/2003",
          email: "dimizen.devmaua@gmail.com",
          area: "Data Science\u00a0;",
          curso: "Ci\u00eancias da Computa\u00e7\u00e3o\u00a0",
          ano: "1\u00b0",
          linkedinLink: "https://www.linkedin.com/in/dimitri-zenaro-1a8279213/",
          githubLink: "http://github.com/Diimy",
        },
        {
          name: "Luigi Guimar\u00e3es Trevisan",
          foto: "https://drive.google.com/uc?id=1U1Vh4qH1GbSRKYVXdYJzjCPmKme-BnAe",
          ra: "22.01102-",
          nascimento: "12/17/2004",
          email: "ltrevisan.devmaua@gmail.com",
          area: "Data Science\u00a0;",
          curso: "Ci\u00eancias da Computa\u00e7\u00e3o\u00a0",
          ano: "1\u00b0",
          linkedinLink: "https://www.linkedin.com/in/luigi-trevisan/",
          githubLink: "https://github.com/LuigiTrevisan",
        },
      ],
    },
    {
      foto: require("./assets/selfMaua.png"),
      name: "Self Maua",
      frontend: "Flutter",
      backend: "Python",
      link: "https://github.com/Maua-Dev/selfie_front.git",

      membros: [
        {
          name: "Bruno Vilardi Bueno",
          foto: "https://drive.google.com/uc?id=1IKIyM5G5jivSx0y7YLnZ-XWD-QvnQ5AC",
          ra: "19.00331-5",
          nascimento: "1/15/2001",
          email: "bvilardi.devmaua@gmail.com",
          area: "DEV;Infra\u00a0;Diretoria\u00a0;",
          curso: "Engenharia de Computa\u00e7\u00e3o\u00a0",
          ano: "4\u00b0",
          linkedinLink:
            "https://www.linkedin.com/in/bruno-vilardi-bueno-8b054a187",
          githubLink: "https://github.com/Brvilardi",
        },
        {
          name: "Hector Guerrini Herrera",
          foto: "https://drive.google.com/uc?id=13epZ3OIVFTK-ZTrOKURe75SaNu8mXQcJ",
          ra: "15.01310-3",
          nascimento: "4/7/1997",
          email: "hguerrini.devmaua@gmail.com",
          area: "Diretoria\u00a0;",
          curso: "Engenharia de Computa\u00e7\u00e3o\u00a0",
          ano: "5\u00b0",
          linkedinLink:
            "https://www.linkedin.com/in/hector-guerrini-herrera-b08007116/",
          githubLink: "https://github.com/hectorguerrini",
        },
        {
          name: "Davi Fernandes Sim\u00f5es Soares",
          foto: "https://drive.google.com/uc?id=13w8Mt0_zhIueTlSXY2qw6yd0ZURFMbBT",
          ra: "20.01099-0",
          nascimento: "7/26/2002",
          email: "dsoares.devmaua@gmail.com",
          area: "DEV;",
          curso: "Engenharia de Computa\u00e7\u00e3o\u00a0",
          ano: "3\u00b0",
          linkedinLink:
            "https://www.linkedin.com/in/davi-fernandes-sim\u00f5es-soares-58299b1a8/",
          githubLink: "https://github.com/Davi-fsS",
        },
        {
          name: "Jo\u00e3o Vitor Choueri Branco",
          foto: "https://drive.google.com/uc?id=15XWC5Lxzc9ae7DAFFhQ7Nhw0B-MxyzSd",
          ra: "21.01075-7",
          nascimento: "10/10/2002",
          email: "jbranco.devmaua@gmail.com",
          area: "DEV;",
          curso: "Engenharia de Computa\u00e7\u00e3o\u00a0",
          ano: "2",
          linkedinLink:
            "https://www.linkedin.com/in/jo%C3%A3o-vitor-choueri-branco-a756ab209",
          githubLink: "https://github.com/JoaoVitorBranco",
        },
        {
          name: "Lucas Duez Verzaro dos Santos",
          foto: "https://drive.google.com/uc?id=1bI4y08CNip0AVPAuT_Igh3d7JJllwtnM&authuser=2",
          ra: "21.00306-8",
          nascimento: "1/10/2002",
          email: "lduez.devmaua@gmail.com",
          area: "DEV;",
          curso: "Ci\u00eancias da Computa\u00e7\u00e3o\u00a0",
          ano: "1\u00b0",
          linkedinLink:
            "https://www.linkedin.com/in/lucas-duez-verzaro-463895208/",
          githubLink: "https://github.com/Lucasdvs10",
        },
        {
          name: "Vitor Guir\u00e3o Soller",
          foto: "https://drive.google.com/uc?id=175FTKhjgzyveOCfWX-7DspFZiZx2v3j0",
          ra: "21.01444-2",
          nascimento: "11/8/2022",
          email: "vsoller.devmaua@gmail.com",
          area: "DEV;",
          curso: "Engenharia de Computa\u00e7\u00e3o\u00a0",
          ano: "2",
          linkedinLink: "https://www.linkedin.com/in/vitor-soller/",
          githubLink: "https://github.com/VgsStudio",
        },
      ],
    },
  ],
};

export default data;
